手动下载release文件
没有靠普的库，

diff --git a/.github/workflows/error_ignore.yml b/.github/workflows/error_ignore.yml
--- a/.github/workflows/error_ignore.yml
+++ b/.github/workflows/error_ignore.yml
@@ -13,17 +13,32 @@ jobs:
         - name: prepare
           run: |
               echo datetime="$(date +'%Y%m%d%H%m%S')" >> $GITHUB_ENV
-        - uses: dsaltares/fetch-gh-release-asset@master
+        - name: download latest release asset
           continue-on-error: true
-          with:
-            repo: ${{ env.GITHUB_REPOSITORY }}
-            version: "latest"
-            file: "test_error_ignore.txt"
-            target: "test_error_ignore.txt.0"
-            token: ${{ secrets.GITHUB_TOKEN }}
+          run: |
+              INPUT_FILE='test_error_ignore.txt'
+              TARGET=$INPUT_FILE
+
+              API_URL="https://${{ secrets.GITHUB_TOKEN }}:@api.github.com/repos/${{ env.GITHUB_REPOSITORY }}"
+              RELEASE_DATA=$(curl $API_URL/releases/latest)
+              MESSAGE=$(echo $RELEASE_DATA | jq -r ".message")
+              if [[ "$MESSAGE" == "Not Found" ]]; then
+                  echo "Release asset not found"
+                  exit 1
+              fi
+              ASSET_ID=$(echo $RELEASE_DATA | jq -r ".assets | map(select(.name == \"${INPUT_FILE}\"))[0].id")
+              if [[ -z "$ASSET_ID" ]]; then
+                  echo "asset not found: $INPUT_FILE"
+                  exit 2
+              fi
+              code=$(curl -w '%{http_code}' -o $TARGET -H 'User-Agent: request module' -H 'Accept: application/octet-stream' "$API_URL/releases/assets/$ASSET_ID")
+              if test "x$code" != "x200"
+              then
+                  rm -rf "$TARGET"
+                  exit 3
+              fi
         - name: job
           run: |
-              cp test_error_ignore.txt.0 test_error_ignore.txt
               echo ${{ env.datetime }} >> test_error_ignore.txt
         - name: create release
           continue-on-error: true
